apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: headlamp
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      targetRevision: 0.45.0
      chart: headlamp
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true